# Generated by Django 4.1.3 on 2022-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/pictures/'),
        ),
    ]
