# Generated by Django 4.1.3 on 2022-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_alter_picture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='../static/images/drawing-brush-logo.png', upload_to='category_images'),
        ),
    ]
