# Generated by Django 4.1.3 on 2022-12-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='drawing-brush-logo.png111', upload_to='category_images/'),
        ),
    ]
