# Generated by Django 4.1.3 on 2022-12-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='drawing-LLLbrush-logo.png', upload_to='category_images/'),
        ),
    ]
