# Generated by Django 4.1.3 on 2022-12-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0011_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
