# Generated by Django 4.1.3 on 2022-12-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0015_alter_aboutus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
